
name: Deploy SpECTRE

on: workflow_dispatch

jobs:
  deploy:
    name: Build and deploy container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: nilsleiffischer/spectre-deploy
          tags: latest
